version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=invoices
      - MYSQL_USER=zola
      - MYSQL_PASSWORD=zola
  zola-api-invoice:
    image: wfadel83/zola-api-invoice
    depends_on:
      - docker-mysql
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=zola
      - DATABASE_PASSWORD=
      - DATABASE_NAME=invoices  
      - DATABASE_PORT=3306
